version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - npm install
      - dotnet build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
 
